version: '3.9'

services:
  db:
    image: 'postgres:15.1-alpine'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    volumes:
      - .:/usr/src/people-server/
    links:
      - 'db:database'
